/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import errors.MaximumFlavorSize;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Cliente;
import models.Pedido;
import models.Pizza;
import models.formas.Circular;
import models.formas.Forma;
import models.formas.Quadrado;
import models.formas.Triangulo;
import models.sabores.Sabor;
import models.tipos.Especial;
import models.tipos.Premium;
import models.tipos.Simples;
import models.tipos.TipoPizza;
import views.combobox.BaseComboBoxModel;
import views.combobox.ClienteComboBoxRenderer;
import views.combobox.FormaComboBoxRenderer;
import views.combobox.SaboresComboBoxRenderer;
import views.tables.BaseTable;
import views.tables.ClienteTable;
import views.tables.PedidoTable;
import views.tables.SaboresTable;
import views.tables.TipoPizzaTable;

/**
 *
 * @author user
 */
public class Pizzaria extends javax.swing.JFrame {

    /* cliente */
    private List<Cliente> clientes;
    private int clientesLinhaSelecionada = -1;
    private BaseTable clientesTableModel = new ClienteTable();
    /* tipos de pizza */
    private List<TipoPizza> tipos;
    private int tipoLinhaSelecionada = -1;
    private BaseTable tiposTableModel = new TipoPizzaTable();
    /* sabores */
    private List<Sabor> sabores;
    private int saborLinhaSelecionada = -1;
    private BaseTable saborTableModel = new SaboresTable();
    /* pedidos */
    private List<Pedido> pedidos;
    private int pedidoLinhaSelecionada = -1;
    private BaseTable pedidoTableModel = new PedidoTable();
    private BaseComboBoxModel clienteComboBoxModel = new BaseComboBoxModel<Cliente>();
    private BaseComboBoxModel saboresComboBoxModel = new BaseComboBoxModel<Sabor>();
    private BaseComboBoxModel formaComboBoxModel = new BaseComboBoxModel<Forma>();

    /* formas */
    private List<Forma> formas;

    /**
     * Creates new form Pizzaria
     */
    public Pizzaria() {
        initComponents();
        /* cliente */
        clientes = new ArrayList<>();

        /* tipos */
        TipoPizza premium = new Premium();
        TipoPizza especial = new Especial();
        TipoPizza simples = new Simples();
        tipos = new ArrayList<>();
        tipos.add(simples);
        tipos.add(especial);
        tipos.add(premium);
        tiposTableModel.atualizarTabela(tipos);

        /* sabores */
        sabores = new ArrayList<>();
        saboresTipoComboBox.addItem(simples);
        saboresTipoComboBox.addItem(especial);
        saboresTipoComboBox.addItem(premium);

        /* pedidos */
        pedidos = new ArrayList<>();

        /* formas */
        formas = new ArrayList<>();
        Forma circular = new Circular();
        Forma quadrado = new Quadrado();
        Forma triangulo = new Triangulo();
        formas.add(circular);
        formas.add(quadrado);
        formas.add(triangulo);
        formaComboBoxModel.atualizar(formas);

    }

    private boolean isClienteFieldsEmpty() {
        return clienteNomeField.getText().isEmpty() || clienteSobreNomeField.getText().isEmpty() || clienteTelefoneField.getText().isEmpty();
    }

    private void limparClientesForm() {
        clienteNomeField.setText("");
        clienteSobreNomeField.setText("");
        clienteTelefoneField.setText("");
        clientesLinhaSelecionada = -1;
        clientesTableModel.atualizarTabela(clientes);
        clienteErrorText.setText("");
    }

    private void preencherClientesForm(Cliente cliente) {
        clienteNomeField.setText(cliente.getNome());
        clienteSobreNomeField.setText(cliente.getSobrenome());
        clienteTelefoneField.setText(cliente.getTelefone());
    }

    private void limparTiposForm() {
        tipoNomeText.setText("");
        tipoPrecoText.setText("");
    }

    private void preencherTiposForm(TipoPizza tipo) {
        tipoNomeText.setText(tipo.getNome());
        tipoPrecoText.setValue(tipo.getPreco());
    }

    private void limparSaboresForm() {
        saboresNomeText.setText("");
        saboresIngredientesText.setText("");
        saboresTipoComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        clientesPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clienteSobreNomeField = new javax.swing.JTextField();
        clienteNomeField = new javax.swing.JTextField();
        clienteTelefoneField = new javax.swing.JTextField();
        clienteExcluirButton = new javax.swing.JButton();
        clienteAtualizarButton = new javax.swing.JButton();
        clienteCadastrarButton = new javax.swing.JButton();
        clienteErrorText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        clientePesquisarText = new javax.swing.JTextField();
        clientePesquisarButton = new javax.swing.JButton();
        clientesLimparButton = new javax.swing.JButton();
        tiposPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tipoPrecoText = new javax.swing.JFormattedTextField();
        tipoNomeText = new javax.swing.JTextField();
        tipoSalvarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tiposTable = new javax.swing.JTable();
        saboresPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        saboresNomeText = new javax.swing.JTextField();
        saboresIngredientesText = new javax.swing.JTextField();
        saboresTipoComboBox = new javax.swing.JComboBox<>();
        saboresSalvarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        saboresTable = new javax.swing.JTable();
        pedidosPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pedidoPizzasText = new javax.swing.JTextArea();
        pedidosClienteComboBox = new javax.swing.JComboBox<>();
        pedidoFormaComboBox = new javax.swing.JComboBox<>();
        dimensaoTextField = new javax.swing.JFormattedTextField();
        pedidoSaboresComboBox = new javax.swing.JComboBox<>();
        pedidoAdicionarPizzaButton = new javax.swing.JButton();
        pedidoSalvarButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        pedidosTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        pedidoPrecoTotal = new javax.swing.JFormattedTextField();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Sobrenome");

        jLabel3.setText("Telefone");

        clienteExcluirButton.setText("excluir");
        clienteExcluirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clienteExcluirButtonMouseReleased(evt);
            }
        });

        clienteAtualizarButton.setText("atualizar");
        clienteAtualizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clienteAtualizarButtonMouseReleased(evt);
            }
        });

        clienteCadastrarButton.setText("cadastrar");
        clienteCadastrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clienteCadastrarButtonMouseReleased(evt);
            }
        });

        clienteErrorText.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(clienteNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clienteSobreNomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(clienteTelefoneField))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clienteErrorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 102, Short.MAX_VALUE)
                                .addComponent(clienteExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clienteAtualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteCadastrarButton)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clienteNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteSobreNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clienteTelefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(clienteErrorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteExcluirButton)
                    .addComponent(clienteAtualizarButton)
                    .addComponent(clienteCadastrarButton))
                .addGap(10, 10, 10))
        );

        clientesTable.setModel(clientesTableModel);
        clientesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clientesTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(clientesTable);

        clientePesquisarButton.setText("pesquisar");

        clientesLimparButton.setText("limpar");
        clientesLimparButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clientesLimparButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(clientePesquisarText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientePesquisarButton))
                    .addComponent(clientesLimparButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientePesquisarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientePesquisarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clientesLimparButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout clientesPanelLayout = new javax.swing.GroupLayout(clientesPanel);
        clientesPanel.setLayout(clientesPanelLayout);
        clientesPanelLayout.setHorizontalGroup(
            clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(clientesPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        clientesPanelLayout.setVerticalGroup(
            clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", clientesPanel);

        jLabel8.setText("Nome");

        jLabel9.setText("Preço (cm²)");

        tipoPrecoText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        tipoNomeText.setEnabled(false);

        tipoSalvarButton.setText("salvar");
        tipoSalvarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tipoSalvarButtonMouseReleased(evt);
            }
        });

        tiposTable.setModel(tiposTableModel);
        tiposTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tiposTableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tiposTable);

        javax.swing.GroupLayout tiposPanelLayout = new javax.swing.GroupLayout(tiposPanel);
        tiposPanel.setLayout(tiposPanelLayout);
        tiposPanelLayout.setHorizontalGroup(
            tiposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tiposPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tiposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tiposPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(tiposPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)))
                .addGroup(tiposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tipoPrecoText)
                    .addComponent(tipoNomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tipoSalvarButton)
                .addContainerGap(495, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        tiposPanelLayout.setVerticalGroup(
            tiposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tiposPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tiposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tipoNomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoSalvarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tiposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tipoPrecoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2))
        );

        jTabbedPane1.addTab("Tipos de pizza", tiposPanel);

        jLabel5.setText("Nome");

        jLabel10.setText("Tipo");

        jLabel11.setText("Ingredientes");

        saboresTipoComboBox.setRenderer(new TipoComboBox());

        saboresSalvarButton.setText("salvar");
        saboresSalvarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                saboresSalvarButtonMouseReleased(evt);
            }
        });

        saboresTable.setModel(saborTableModel);
        jScrollPane3.setViewportView(saboresTable);

        javax.swing.GroupLayout saboresPanelLayout = new javax.swing.GroupLayout(saboresPanel);
        saboresPanel.setLayout(saboresPanelLayout);
        saboresPanelLayout.setHorizontalGroup(
            saboresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saboresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saboresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                    .addGroup(saboresPanelLayout.createSequentialGroup()
                        .addGroup(saboresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(saboresPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(saboresNomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, saboresPanelLayout.createSequentialGroup()
                                .addGroup(saboresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(saboresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(saboresIngredientesText)
                                    .addComponent(saboresTipoComboBox, 0, 190, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(saboresSalvarButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        saboresPanelLayout.setVerticalGroup(
            saboresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saboresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saboresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(saboresNomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saboresSalvarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saboresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(saboresIngredientesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saboresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(saboresTipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sabores", saboresPanel);

        jLabel4.setText("Cliente");

        jLabel6.setText("Forma");

        jLabel12.setText("Dimensao");

        jLabel13.setText("Sabores");

        jLabel14.setText("Preço total");

        jLabel15.setText("Pizzas do pedido");

        pedidoPizzasText.setColumns(20);
        pedidoPizzasText.setRows(5);
        jScrollPane4.setViewportView(pedidoPizzasText);

        pedidosClienteComboBox.setModel(clienteComboBoxModel);
        pedidosClienteComboBox.setRenderer(new ClienteComboBoxRenderer());

        pedidoFormaComboBox.setModel(formaComboBoxModel);
        pedidoFormaComboBox.setRenderer(new FormaComboBoxRenderer());

        pedidoSaboresComboBox.setModel(saboresComboBoxModel);
        pedidoSaboresComboBox.setRenderer(new SaboresComboBoxRenderer());

        pedidoAdicionarPizzaButton.setText("adicionar pizza");
        pedidoAdicionarPizzaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pedidoAdicionarPizzaButtonMouseReleased(evt);
            }
        });

        pedidoSalvarButton.setText("salvar");

        pedidosTable.setModel(pedidoTableModel);
        jScrollPane5.setViewportView(pedidosTable);

        jButton5.setText("pesquisar");

        pedidoPrecoTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        pedidoPrecoTotal.setEnabled(false);

        javax.swing.GroupLayout pedidosPanelLayout = new javax.swing.GroupLayout(pedidosPanel);
        pedidosPanel.setLayout(pedidosPanelLayout);
        pedidosPanelLayout.setHorizontalGroup(
            pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedidosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(pedidosPanelLayout.createSequentialGroup()
                        .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pedidosPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addComponent(pedidosClienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pedidoAdicionarPizzaButton))
                            .addComponent(jLabel6)
                            .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pedidoFormaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pedidosPanelLayout.createSequentialGroup()
                                    .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pedidosPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(pedidosPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(17, 17, 17)))
                                    .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dimensaoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(pedidoSaboresComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(pedidoPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pedidoSalvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pedidosPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pedidosPanelLayout.setVerticalGroup(
            pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedidosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pedidoSalvarButton)
                    .addGroup(pedidosPanelLayout.createSequentialGroup()
                        .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel15)
                            .addComponent(pedidosClienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pedidoAdicionarPizzaButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pedidoFormaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(dimensaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(pedidoSaboresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pedidoPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pedidos", pedidosPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteCadastrarButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteCadastrarButtonMouseReleased
        if (clientesLinhaSelecionada != -1) {
            return;
        }
        if (isClienteFieldsEmpty()) {
            clienteErrorText.setText("Todos os campos sao obrigatorios!");
            return;
        }
        Cliente cliente = new Cliente();
        cliente.setNome(clienteNomeField.getText());
        cliente.setSobrenome(clienteSobreNomeField.getText());
        cliente.setTelefone(clienteTelefoneField.getText());
        clientes.add(cliente);
        clientesTableModel.adicionar(cliente);
        clienteComboBoxModel.adicionar(cliente);

        limparClientesForm();
    }//GEN-LAST:event_clienteCadastrarButtonMouseReleased

    private void clienteAtualizarButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteAtualizarButtonMouseReleased
        if (clientesLinhaSelecionada == -1) {
            return;
        }
        if (isClienteFieldsEmpty()) {
            clienteErrorText.setText("Todos os campos sao obrigatorios!");
            return;
        }

        Cliente cliente = this.clientes.get(clientesLinhaSelecionada);

        cliente.setNome(clienteNomeField.getText());
        cliente.setSobrenome(clienteSobreNomeField.getText());
        cliente.setTelefone(clienteTelefoneField.getText());

        clientesTableModel.atualizarTabela(this.clientes);
        clienteComboBoxModel.atualizar(this.clientes);

        limparClientesForm();
    }//GEN-LAST:event_clienteAtualizarButtonMouseReleased

    private void clientesTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesTableMouseReleased
        // preenche form com dados do cliente selecionado
        clientesLinhaSelecionada = clientesTable.getSelectedRow();
        if (clientesLinhaSelecionada == -1) {
            return;
        }
        Cliente cliente = this.clientes.get(clientesLinhaSelecionada);

        preencherClientesForm(cliente);
    }//GEN-LAST:event_clientesTableMouseReleased

    private void clientesLimparButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesLimparButtonMouseReleased
        limparClientesForm();
    }//GEN-LAST:event_clientesLimparButtonMouseReleased

    private void clienteExcluirButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteExcluirButtonMouseReleased
        if (clientesLinhaSelecionada == -1) {
            return;
        }
        Cliente cliente = this.clientes.get(clientesLinhaSelecionada);

        this.clientes.remove(cliente);

        clientesTableModel.remover(cliente);
        clientesTableModel.atualizarTabela(this.clientes);
        clienteComboBoxModel.remover(cliente);

        limparClientesForm();
    }//GEN-LAST:event_clienteExcluirButtonMouseReleased

    private void tipoSalvarButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoSalvarButtonMouseReleased
        if (tipoLinhaSelecionada == -1) {
            return;
        }
        TipoPizza tipo = this.tipos.get(tipoLinhaSelecionada);

        double preco = Double.parseDouble(tipoPrecoText.getValue().toString());
        tipo.setPreco(preco);
        tiposTableModel.atualizarTabela(this.tipos);

        limparTiposForm();
    }//GEN-LAST:event_tipoSalvarButtonMouseReleased

    private void tiposTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiposTableMouseReleased
        tipoLinhaSelecionada = tiposTable.getSelectedRow();
        if (tipoLinhaSelecionada == -1) {
            return;
        }
        TipoPizza tipo = this.tipos.get(tipoLinhaSelecionada);

        preencherTiposForm(tipo);
    }//GEN-LAST:event_tiposTableMouseReleased

    private void saboresSalvarButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saboresSalvarButtonMouseReleased
//        saborLinhaSelecionada = saboresTable.getSelectedRow();
//        if (saborLinhaSelecionada == -1) {
//            return;
//        }
        String nome = saboresNomeText.getText();
        String ingredientes = saboresIngredientesText.getText();
        TipoPizza tipo = (TipoPizza) saboresTipoComboBox.getSelectedItem();

        Sabor sabor = new Sabor(nome, ingredientes, tipo);
        sabores.add(sabor);
        saborTableModel.adicionar(sabor);
        saboresComboBoxModel.adicionar(sabor);

        limparSaboresForm();
    }//GEN-LAST:event_saboresSalvarButtonMouseReleased

    private void pedidoAdicionarPizzaButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidoAdicionarPizzaButtonMouseReleased
        Cliente cliente = (Cliente) pedidosClienteComboBox.getSelectedItem();

        Pizza pizza = new Pizza();
        Forma forma = (Forma) pedidoFormaComboBox.getSelectedItem();
        pizza.setForma(forma);

        Sabor sabores[] = (Sabor[]) pedidoSaboresComboBox.getSelectedObjects();
        for (Sabor sabor : sabores) {
            try {
                System.out.println("sabor" + sabor.getNome());
                pizza.addSabor(sabor);
            } catch (MaximumFlavorSize ex) {
                // atingiu o numero maximo de 2 sabores
                Logger.getLogger(Pizzaria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_pedidoAdicionarPizzaButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clienteAtualizarButton;
    private javax.swing.JButton clienteCadastrarButton;
    private javax.swing.JLabel clienteErrorText;
    private javax.swing.JButton clienteExcluirButton;
    private javax.swing.JTextField clienteNomeField;
    private javax.swing.JButton clientePesquisarButton;
    private javax.swing.JTextField clientePesquisarText;
    private javax.swing.JTextField clienteSobreNomeField;
    private javax.swing.JTextField clienteTelefoneField;
    private javax.swing.JButton clientesLimparButton;
    private javax.swing.JPanel clientesPanel;
    private javax.swing.JTable clientesTable;
    private javax.swing.JFormattedTextField dimensaoTextField;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton pedidoAdicionarPizzaButton;
    private javax.swing.JComboBox<Forma> pedidoFormaComboBox;
    private javax.swing.JTextArea pedidoPizzasText;
    private javax.swing.JFormattedTextField pedidoPrecoTotal;
    private javax.swing.JComboBox<Sabor> pedidoSaboresComboBox;
    private javax.swing.JButton pedidoSalvarButton;
    private javax.swing.JComboBox<Cliente> pedidosClienteComboBox;
    private javax.swing.JPanel pedidosPanel;
    private javax.swing.JTable pedidosTable;
    private javax.swing.JTextField saboresIngredientesText;
    private javax.swing.JTextField saboresNomeText;
    private javax.swing.JPanel saboresPanel;
    private javax.swing.JButton saboresSalvarButton;
    private javax.swing.JTable saboresTable;
    private javax.swing.JComboBox<TipoPizza> saboresTipoComboBox;
    private javax.swing.JTextField tipoNomeText;
    private javax.swing.JFormattedTextField tipoPrecoText;
    private javax.swing.JButton tipoSalvarButton;
    private javax.swing.JPanel tiposPanel;
    private javax.swing.JTable tiposTable;
    // End of variables declaration//GEN-END:variables
}
